# android.yml 
# base code from https://github.com/jaredtao/HelloActions-Qt

name: Android
on: 
  push:
    paths-ignore:
      - 'Example.md'
      - 'HowToSetProject.ko.md'
      - 'HowToSetProject.md'
      - 'README.ko.md'
      - 'README.md'
      - 'TestEnv.md'
      - 'ToTest.md'
      - 'ToUpgrade.md'
      - 'Vision.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'Example.md'
      - 'HowToSetProject.ko.md'
      - 'HowToSetProject.md'
      - 'README.ko.md'
      - 'README.md'
      - 'TestEnv.md'
      - 'ToTest.md'
      - 'ToUpgrade.md'
      - 'Vision.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        qt_ver: [5.12.10]
        qt_target: [android]
        qt_arch: [android_x86,android_armv7,android_arm64_v8a]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build android
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          cd HelloAndroid
          qmake
          make
